workspace:
  base: /site

pipeline:
  frontend:
    image: node:6
    commands:
      - npm install
      - npm run-script build 
  s3-sync:
    image: plugins/s3-sync:1
    bucket: nathanmalishev.com
    region: ap-southeast-2
    acl: public-read
    access_key: ${AWS_ACCESS_KEY_ID}
    secret_key: ${AWS_SECRET_ACCESS_KEY}
    source: build/.
    target: /
    delete: true
