version: 0.2
phases:
  build:
    commands:
      - npm install
      - npm run-script build 
  post_build:
    commands:
      - printenv
      - aws s3 cp build s3://nathanmalishev.com/ --recursive
